# Generated by Django 4.2.11 on 2024-08-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("user_seq", models.AutoField(primary_key=True, serialize=False)),
                ("birth", models.DateField()),
                ("id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("profile_url", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("SENIOR", "Senior"),
                            ("YOUTH", "Youth"),
                        ],
                        max_length=6,
                    ),
                ),
                ("sex", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("interest", models.CharField(max_length=255)),
                ("personality", models.CharField(max_length=255)),
                ("career", models.CharField(max_length=255)),
                ("hobby", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "user_info",
            },
        ),
        migrations.CreateModel(
            name="UserEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_embedding", models.JSONField()),
                ("career_embedding", models.JSONField()),
                ("hobby_embedding", models.JSONField()),
                ("interest_embedding", models.JSONField()),
                ("personality_embedding", models.JSONField()),
                (
                    "user_info",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matching.userinfo",
                    ),
                ),
            ],
        ),
    ]
